######################################
# see https://yamllint.readthedocs.io/en/stab
# https://github.com/adrienverge/ya
# and https://github.com/ibiqlik/action-yamllint

---
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

extends: "default"

rules:
  line-length:
    max: 160
    level: "error"
  document-end:
    level: "warning"
  empty-values:
    level: "warning"
  comments-indentation: "disable"
#  key-ordering:
#    level: "warning"
  octal-values:
    level: "warning"
  quoted-strings:
    level: "warning"
...
